DROP TABLE IF EXISTS news;

CREATE TABLE news (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	image BLOB
);